### ISSUE TITLE
HH_Container_LCTRL Error

### ISSUE THREAD

**Issue by Wycliffe-Julia-Torres** [SalesforceFoundation/EDA#1079]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Report a Bug

* **What is the current behavior?**
Error:
You do not have access to the Apex class named 'HH_Container_LCTRL'.

**Given**: When a user with a profile that is not the system admin profile goes to a household account record

**When**: From the household account record, the user will click the Manage Household button

**Then**: The user will receive an error that reads: You do not have access to the Apex class named 'HH_Container_LCTRL'.

**And When**: A system admin profile user recreates the steps above, no error is generated.

**Then**: Found that 'HH_Container_LCTRL is apex class managed by NPSP. There were no critical update alerts that indicated that this Apex controller would be affected by sharing behavior.

**Comment by lifewithryan** [comment]
@jacebryan @jesslopez-sf looks like this may have been filed against the EDA repo, but sounds like it might be an NPSP thing?

**Comment by jesslopez-sf** [comment]
Hi @Wycliffe-Julia-Torres , we don't provide support here on Github (the Power of Us Hub is best). I do know that this error is caused by Profiles not having access to that Apex class. There was a Critical Update that recently required this. Our NPSP troubleshooting page has the full list of Apex classes that you will need to grant access for: https://powerofus.force.com/s/article/NPSP-Troubleshooting#ariaid-title7
