### ISSUE TITLE
Affiliation mappings translations not working

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#320]
From https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000002xSF9X

I am translating HEDA into spanish using workbench, and when I create an primary affiliation, the corresponding  lookup field in the contact is not being completed. I tried creating new affiliations mapings through HEDA Settings  using the account record type and contact field in spanish but it's not working. When I change my configuration to English works perfectly.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjDgAAI" target="_blank">W-011374</a>

**Comment by rosariolacle** [comment]
Hi! I made this work changing only the fields at Affiliations Mappings. Record types remain in english and fileds in spanish.

**Comment by ceiroa** [comment]
The root of the issue is that the Affiliation Type field in Affiliation (Affiliation_Type__c) is a formula that is storing the record type name of the parent Account:

`Account__r.RecordType.Name
`
This name field is the original field name, not the translated one. Thus it wouldn't match a translation stored in the Affiliation Mapping settings. The record type names in the Affiliation Settings need to be kept in the original language of the record types for the mappings to work. 

There is no formula method I'm aware of that can return the translated value of a record type (like the toLabel() method in SOQL). Thus the best option seems to be to employ the workaround @rosariolacle provided, and enter the primary field translations in the Affiliation Mappings, but keep the account record types in english.

Does this seem reasonable, @kbromer? The workaround mentioned is straightforward, and the alternative would be to find the english original names for all account record types at runtime, which would be elaborate.

**Comment by jacebryan** [comment]
Reopening issue based on this PUB Thread (https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000DA0Q&fId=0D58000003k5yjk) after speaking with @xinnanlisf and @ceiroa 

**Gonzalo Gómez de la Cal (S4G Consulting)**
_There is no translation possible for the Picklist values of Affiliation Type neither in Translation workbench or in Substitution for the HEDA Package. If we set up our org in Spanish, the primary affiliation fields in the Contact are translated, but those fields are not updating automatically when you create a primary Affiliation.

To reproduce the issue, translate primary affiliation fields to Spanish, setup the org(user) in Spanish language and create a new primary affiliation of one of the set types."_

The previously identified workout for this (https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000002xSF9X) stated "I tried changing the lookup fields at the settings and it works. The record types are in english and the fields in Spanish."  

**Per Gonzalo Gómez de la Cal (S4G Consulting)**
_"The workaround in that thread would only work for Spanish, but I need it to work simultaneously in both Spanish and English, as I have international clients... If I make the translations of the HEDA Settings to Spanish, I lose the English ones."_

**Comment by jofsky** [comment]
Included in production release 1.91

**Comment by luisigualada** [comment]
I am using EDA in Spanish and have done some translations on EDA fields to fit my client's nomenclature.

I have created an Academic Program type account and it lets me create it correctly, but then when I go to edit it it always shows me the following error
![image](https://user-images.githubusercontent.com/4295350/94919091-223d5000-04b4-11eb-9b87-7cb1486910c2.png)

I have also created 3 record types on contact.
It allows me to create the contact without problems, but when I then go to the related lists and try to create a new affiliation and check the main affiliation check, it shows me the same error again, without allowing me to create the affiliation with the previously created account.
![image](https://user-images.githubusercontent.com/4295350/94919294-911aa900-04b4-11eb-91bc-074c0089ebb8.png)

This is how I have configured my affiliation assignments. I have copied in the main contact affiliation field the api name of the fields as you comment, but it still doesn't work.
![image](https://user-images.githubusercontent.com/4295350/94919558-f4a4d680-04b4-11eb-82ce-298eca082180.png)

Finally, I also have problems when I try to edit a contact that has already been created. It tells me that we cannot find the phone specified in Preferred Phone. Make sure you are entering the field label of an existing Custom Phone field.
I have all of the phone fields filled in and select from the picklist which is the preferred phone field and still get the error skipped.

I have noticed that when I change my user's language to English, all these problems I am talking about mysteriously disappear.
Can someone explain to me if all this is due to an EDA Bug or what I am configuring wrong?

![image](https://user-images.githubusercontent.com/4295350/94919785-52392300-04b5-11eb-84d4-922d13203b46.png)

I've already spent enough hours researching what the problem might be without any success.

Thanks in advance.

**Comment by jamesbsfdc** [comment]
Hi Luis

Sorry to hear you are encountering issues. Unfortunately we don't provide support via GitHub. Please could you create a new post for this on the EDA group in the Power of Us Hub: https://powerofus.force.com/s/group/0F980000000D6ujCAC/education-data-architecture

Thanks
