### ISSUE TITLE
Nested terms

### ISSUE THREAD

**Issue by angelaaddison** [SalesforceFoundation/EDA#413]
Most institutions I think would need parent/child terms. What we've done in our app is enhance the model to include a lookup field to the parent term record (so you can have more than one level down), as well as an ordinal so that you can use for longitudinal reporting and displays in business order which isn't necessarily the same as calendar date order. This allows for the academic year > academic term > academic session > etc. to be term types which we have and then you can also create other non-academic measurement periods that you might use in like enrollment period, pre-admission window, etc.

**Comment by jacebryan** [comment]
@angelaaddison - This is a great post for a HEDA Idea! I say this because what you are describing, to me, is new functionality vs. a bug you encountered in HEDA.

Some background on the use of Github (when it comes to HEDA) can be found here in case you are interested: https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000CCE1k&tab=sfdc.ProfilePlatformFeed&fId=0D58000003LK7N3

Can you please post your Idea here? https://powerofus.force.com/hub-ideas?product=HEDA

Thank you!

**Comment by jacebryan** [comment]
@angelaaddison - thank you for posting this as a HEDA Idea! https://powerofus.force.com/hub-ideas/1201

@davidjray - feel free to close this issue.

**Comment by lifewithryan** [comment]
Reopening issue as this is going to be in the next release of HEDA. (So essentially will open/close) all together.

**Comment by jacebryan** [comment]
@lifewithryan - did you want to close this Issue since it rolled into 1.67?

**Comment by robertbwatson** [comment]
Closing this since we've now delivered this issue/idea.
