### ISSUE TITLE
Update SRS document

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#431]
Some of the technical sections of the SRS, such as the one about error handling, are outdated. We need to update them.

https://powerofus.force.com/articles/Resource/Higher-Education-Data-Architecture-HEDA-Software-Requirements-Specification

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PLdaAAG" target="_blank">W-018709</a>

**Comment by ceiroa** [comment]
Addresses section also needs to be updated, as we now (since version 1.15) also support addresses in Contact.

https://github.com/SalesforceFoundation/HEDAP/issues/245
https://github.com/SalesforceFoundation/HEDAP/pull/255

**Comment by ceiroa** [comment]
Course Enrollment info needs to be updated to reflect renaming as Course Connection to support multiple faculty, etc related to a course: https://github.com/SalesforceFoundation/HEDAP/pull/300

**Comment by kmbzoo** [comment]
Is this the only documentation for Heda specifications?  I am trying to find the changes between Heda v1.13 and the newest version we want to upgrade to - v1.5.0.

**Comment by jacebryan** [comment]
@kmbzoo  - Sorry for the late response! And yes - the SRS is the only HEDA specifications document. For the managed package version of HEDA you will want to review the [Release Notes](https://github.com/SalesforceFoundation/HEDAP/releases) to see what changes and/or issues have been addressed with each version release. For reference - we do not support the unmanaged version of HEDA (i.e. code you fork or clone from Github) and because of this we do not have a document the outlines the changes between HEDA versions.

**Comment by robertbwatson** [comment]
@aligeez  @jacebryan  Are we able to close this issue now?

**Comment by aligeez** [comment]
@robertbwatson - we are mid-SRS retirement at the moment, probably half way done. That being said, it will be an ongoing project into the end of summer and we can probably close this ticket.

**Comment by jacebryan** [comment]
@robertbwatson @aligeez - Closing Issue now.
