### ISSUE TITLE
Remove version-specific code from install script

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#476]
Nobody should be in an older HEDA version since they are all push-upgraded.

WARNING: we need to check if the push upgrade has been consistently failing for any specific org.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007qP38AAE" target="_blank">W-020074</a>

**Comment by ceiroa** [comment]
IF push upgrades have been failing for some orgs, we should NOT do this work. We have to wait for the release engineering team ( @jlantz , @cpolcyn  ) to decide on what to do there and potentially put in place a process to keep track of HEDA orgs that are failing to get to the latest version, and help them upgrade.

We should do this work (remove this outdated code from the install script) once every production org in the latest version. This item does NOT cover getting all orgs to the latest version.

**Comment by cpolcyn** [comment]
Release engineering has never guaranteed that push upgrades will be successful for every org. That's not really something we can do, since orgs may fail to upgrade due to things out of our control, e.g. customizations done by the org admins. The failure rate for HEDA push upgrades is usually between 2% and 5% but it is never 0%. Our policy has been that if a customer seeks help we will work with community manager to resolve the issue.

We definitely want to track push failures across all projects so that we can be proactive, but that may be a long way off still. Even after we have that in place we still probably won't get to 0% failure rate, because there will be some orgs where customer action is needed and we are unable to get them to do it for whatever reason.

**Comment by MatthewBlanski** [comment]
Given the low risk involved in this and the LOE to track this down in every use case, this is no longer in our backlog.
