### ISSUE TITLE
Error creating a contact: We can't find the Phone specified in Preferred Phone en version 1.83

### ISSUE THREAD

**Issue by jlalmazan** [SalesforceFoundation/EDA#935]
When I try to create a contact in my sandbox org, Salesforce throws the following error: "We can't find the Phone specified in Preferred Phone. Make sure that you're entering the field label of an existing custom Phone field.". However, I am creating contact with all the data completed.

This error occurred today, yesterday everything worked correctly. Just, today the version of EDA was updated to version 1.83 in my sandbox org.

**Comment by jacebryan** [comment]
Hi @jlalmazan - can you provide me with the steps to replicate the issue? Can you also let me know if Disable Preferred Phone enforcement is checked or unchecked in EDA Settings?

**Comment by jacebryan** [comment]
@jlalmazan - from that error message it looks like there is a mismatch between the value in the Preferred Email pick list and the available field labels on Contact.

For example:

1. Add the value of 'test' to the Preferred Email picklist on Contact.
2. Create a contact and select 'test' as the value for Preferred Email
3. Add '555-555-5555' to the Phone field
4. Click save

This error appears because 'test' does not match the label of an existing custom Phone field. This is the same behavior in place for Preferred Email.

Let me know if that is what you see in your SB org.
